name: Secondary Workflow

on:
  push:
    branches:
      - main  # Define the branch you want to trigger on

jobs:
  secondary-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     
